language: perl

perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
env:
  - "AUTHOR_TESTING=1 AUTOMATED_TESTING=1"
install:
    - "cpanm -n Test::More Test::Pod Test::Pod::Coverage"
    - dzil authordeps --missing | cpanm --notest || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --notest || { cat ~/.cpanm/build.log ; false ; }
sudo: false
notifications:
  email: false
script:
    - dzil smoke --author --release
