language: perl

perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

before_install:
    - cpanm Dist::Zilla --quiet --notest

install:
    - dzil authordeps | xargs cpanm --quiet --notest
    - dzil listdeps | xargs cpanm --quiet --notest

script:
    - dzil smoke --release --author --automated
